### ISSUE TITLE
bilibili网页闪烁问题反馈Edge

### ISSUE THREAD

**Issue by Tau01** [polywock/globalSpeed#426] opened 2023-10-19 11:40 UTC
视频太于10MB上传不了，投bilibili了
https://www.bilibili.com/video/BV1Up4y1T7Cs/
https://www.bilibili.com/video/BV1KN411t75C/
书签如图
![视频1截图 ](https://github.com/polywock/globalSpeed/assets/111262227/8dc9e5b3-e072-4716-809c-187a8be98571)
![视频2截图](https://github.com/polywock/globalSpeed/assets/111262227/d7263597-e486-4ec1-9bcf-d518ff88a275)
再加两张闪烁图
![屏幕截图 2023-10-19 193030](https://github.com/polywock/globalSpeed/assets/111262227/b71ee113-e51e-4d53-8d81-12108da1563a)
![屏幕截图 2023-10-19 192909](https://github.com/polywock/globalSpeed/assets/111262227/34072dd7-c20f-405f-8a82-cff9a33b9f3e)
只有在视频播放页会闪烁，看评论时要把我闪瞎了，哔哩哔哩的直播页面和动态不会闪烁

**Comment by polywock** [comment] 2023-10-19 18:40
Hello. Interesting problem. Have you confirmed this issue is related to Global Speed? If not, try to fully disable Global Speed to check if the issue stops.

**Comment by Tau01** [comment] 2023-10-20 01:32
Yes, I am sure this issue is related to Global Speed. The recorded video that Global Speed is fully disabled  has been uploaded to bilibili for comparison. The issue doesn't exist any more.
https://www.bilibili.com/video/BV1GC4y1373R/

**Comment by polywock** [comment] 2023-10-20 02:14
Nvidia graphics card? Seems to be a similar issue. 

https://www.bilibili.com/video/BV12H4y1Z7mD

https://bugs.chromium.org/p/chromium/issues/detail?id=1155285

**Comment by Tau01** [comment] 2023-10-20 05:08
That is true. After changing (edge://flags/#use-angle) to D3D9, the issue temporarily disappeares.
![D3D9](https://github.com/polywock/globalSpeed/assets/111262227/61e63399-b211-4820-8f3c-6650df26ffe0)
![solution](https://github.com/polywock/globalSpeed/assets/111262227/d5fcd038-bca4-4a27-ba17-27dcd8eaab38)

**Comment by polywock** [comment] 2023-10-20 05:45
Hello. I think I know why Global Speed is having a impact. If you want, try reverting the edge://flags change and try this version of Global Speed. Hopefully this version fixes the issue. 

[packed.zip](https://github.com/polywock/globalSpeed/files/13050405/packed.zip)

1. Uninstall or disable the original Global Speed. 
1. Download packed.zip and extract the folder. 
2. open extensions page, edge://extensions 
4. Enable developer mode on the left (Edge) 
5. Once developer mode is enabled, you should see "load unpacked". Click on that and load the extracted folder.

**Comment by Tau01** [comment] 2023-10-20 07:36
I tried your packed, but it doesn't work normally on the bilibili video. Nothing happened after I adjusted the speed or used the keyboard to seek as uasual. Emm, only the display on the icon of extension itself changed, but it doesn't really work on the video.

**Comment by polywock** [comment] 2023-10-20 07:49
Interesting. That could be due to these 3 reasons. 
1. The old version of Global Speed is still running at 1x so speed never changes. 
2. The webpage wasn't refreshed after loading the new version. 
3. The video is playing as a CANVAS player instead of VIDEO player. This might be due the format you set on Bilibili. They have options like HEVC, AVC, AV1. Have you tried changing that?

**Comment by Tau01** [comment] 2023-10-20 09:07
For the previous two points, I have disabled the old version and then refreshed. Next, I enabled the new one, then I refreshed the page again. It just doesn't work.
For comparison, I tried it in another way that I disabled the old version after setting the speed on 2x, then refreshing the webpage made the video speed turned back to 1x automatically. So, I think the first point doesn't affect.
As for the third point, sorry, I can't find the configuration of it. I don't know why my option of it disappeared.
This is other's
![屏幕截图 2023-10-20 165544](https://github.com/polywock/globalSpeed/assets/111262227/9297e0bb-bf38-4d0f-9231-3b72e1684097)
This is mine
![屏幕截图 2023-10-20 165613](https://github.com/polywock/globalSpeed/assets/111262227/3beccfa3-77d9-448a-b6fe-6f4e4514f071)

**Comment by Tau01** [comment] 2023-10-20 11:15
Well, I test it for a little long time on each fomat, AV1, HEVC and AVC. The result is that the issue isn't solved by this packed version. 
Besides, this packed version doesn't work on HEVC, while the old one from the edge extension store work well on HEVC.
Maybe just waiting for Nvidia's news?

**Comment by R-JeffreyKing** [comment] 2023-12-22 12:27
Got exactly the same problem. Having tried everything he did before, still doesn't work well but found out that I'm not alone at least lol.

**Comment by polywock** [comment] 2024-12-21 18:33
Since it's a Nvidia driver issue I presume the issue is fixed by now. Let me know if otherwise.

**Closed by polywock** 2024-12-21 18:33 UTC
