### ISSUE TITLE
Toggle velocity feature is missing

### ISSUE THREAD

**Issue by Perisc0** [polywock/globalSpeed#504] opened 2024-05-24 04:03 UTC
I can't toggle between the 1 velocity and custom velocity.
Example:
I use NumpadSubtract to decrease veloticy, NumpadAdd to increase and NumpadComma to toggle from the current velocity and normal velocity (1).
![brave_oknYVcSaZJ](https://github.com/polywock/globalSpeed/assets/55250285/e1882c55-fddb-4293-bf32-8e722cc20486)

**Comment by polywock** [comment] 2024-05-24 04:30
Hi.I had to rewrite the extension for the Manifest V3 update, which required substantial changes. I forgot to implement the toggle velocity feature.  This issue was fixed recently and will be updated to the Chrome Web Store within a week.

**Comment by TrexPD** [comment] 2024-05-24 06:08
I'm also missing this feature, where let's say I'm at the current speed of **"1.8"** and pressing CTRL+S would return me to the default **"1.0"** and vice versa. I've created a temporary alternative until a possible update of the extension in the photo below:
![Captura de tela 2024-05-24 025822](https://github.com/polywock/globalSpeed/assets/66758838/2ba76e2c-63c3-4780-a15a-567fb4051584)

**Comment by polywock** [comment] 2024-05-24 11:28
@TrexPD @Perisc0 Fixed in the latest update. I only rolled the update for 10% of users so you probably won't automatically get it. You'll have to click Update on this page > chrome://extensions

**Comment by ArtTim** [comment] 2024-05-24 13:53
Hi!

These settings used to work independently of each other. 
For example, user speed control was assigned to the S key. And the Ctr+S key combination was assigned to activate a predefined speed (e.g. x4). When you pressed S, the user speed was switched on (e.g. x3), and when you pressed it again, the speed returned to the base speed - x1. When pressing Ctr+S, the speed x4 was switched on, and when pressing again, the base speed x1 was switched on. 
Now, if you switch to x3 (S key) and then x4 (Ctr+S key), the S key turns on the x4 speed. Previously it would have turned on x3.

Can you make these toggles independent again, please?

**Comment by Perisc0** [comment] 2024-05-24 17:54
> @TrexPD @Perisc0 Fixed in the latest update. I only rolled the update for 10% of users so you probably won't automatically get it. You'll have to click Update on this page > chrome://extensions

Solved. Thanks.

**Comment by ArtTim** [comment] 2024-05-24 21:48
> @ArtTim Have you updated to the latest version? I only rolled out the update to 10% of users so you'll have to manually update by clicking Update on this page > chrome://extensions

@polywock Yes, I did. I have version 3.05. 
Normal speed switchs normally. Thanks for the quick solution to this problem.
The problem is a bit different. The S key toggles the base speed by default. I added another speed switch to the Ctr+S key, this enables the preset x4 speed. And now if I switch to x4 (Ctr+S) when the base speed is enabled (like x2), the S key will start switching between x1 and x4 speeds. Whereas before, the S key would switch x1 and x2 speeds, and the Ctr+S key would switch x1 and x4. That is, they were independent. Now S memorizes the value for Ctr+S.

S key settings
![image](https://github.com/polywock/globalSpeed/assets/27860674/a1d0944b-1e8c-4bb9-83e9-0517cc20c2b6)
Ctr+S key settings
![image](https://github.com/polywock/globalSpeed/assets/27860674/61ed5233-6d72-4696-bd30-0593267d9ed4)

**Comment by polywock** [comment] 2024-05-25 07:56
@ArtTim There was a minor issue with 5.0.5 that might be a potential cause. You can update to 5.0.7 by going to `chrome://extensions`, enabling Developer mode and clicking Update. 

I can't seem to reproduce the issue in the latest version. Please provide a step by step instruction. 

What I tried -> Start at 1 -> Changed speed to 2x using Global Speed menu -> Used S key -> Speed is now 1x -> Used S key again -> Speed is now 2x -> Used Ctrl-S key -> Speed is now 4 -> Used Ctlr-S key again -> Speed is now 2.

**Comment by ArtTim** [comment] 2024-05-25 16:17
> @ArtTim There was a minor issue with 5.0.5 that might be a potential cause. You can update to 5.0.7 by going to `chrome://extensions`, enabling Developer mode and clicking Update.
> 
> I can't seem to reproduce the issue in the latest version. Please provide a step by step instruction.
> 
> What I tried -> Start at 1 -> Changed speed to 2x using Global Speed menu -> Used S key -> Speed is now 1x -> Used S key again -> Speed is now 2x -> Used Ctrl-S key -> Speed is now 4 -> Used Ctlr-S key again -> Speed is now 2.

Now it's exactly the way it worked before. Thank you very much, issue solved!
Your extension is one of the most important in my collection. Thank you very, very much!

**Comment by TrexPD** [comment] 2024-05-26 01:53
I updated the extension to **3.0.7** and apparently everything is working normally, I really liked the new "show indicator", congratulations your extension is one of my favorites, thank you very much for your contribution!

I have a few questions: 
1. The Firefox version has not yet received the update (Yes, I forced the update), when will it receive it? 
    Version: 2.9.9971
    Last Updated: November 19, 2023

2. I can't import my Brave Browser settings into Firefox, could this be because Firefox isn't at version 3?

Translated with DeepL.com (free version)

**Comment by polywock** [comment] 2024-05-26 02:43
@TrexPD Thanks! The Chrome Web Store's deadline was June, so that's why it's only published for Chrome. Once all the bugs are sorted, I'll also publish on Firefox and Edge. Maybe a month or so later. 

>  could this be because Firefox isn't at version 3?

Pretty much! You can't import settings from newer versions of Global Speed. The current "setting version" on the Chrome Web Store is 11, but 10 on Firefox.

**Closed** 2024-06-01 08:24 UTC
