### ISSUE TITLE
Issue with the latest Edge browser

### ISSUE THREAD

**Issue by Rangtian** [polywock/globalSpeed#56] opened 2021-01-28 03:31 UTC
Sometimes the video just rushes to the end of the buffer and stuck, while the audio plays at the target speed normally.

x3 can reproduce this frequently, more often than x2.

Both Youtube and Bilibili video play suffer.

Don't know if videos on other sites suffer.

**Comment by polywock** [comment] 2021-01-28 09:44
Thanks for the feedback. Sorry to hear about the issue. I tried reproducing the behavior but I'm not having any success. I'll use Edge Chromium as my daily driver for a while to see if I could reproduce it.  I'll also pin this issue to ask if anyone else is experiencing the same problem. 

Also if you have time and if it's convenient for you... 

1. Add a new 'test' Profile to Edge. This profile should not have any extensions except Global Speed. Do you still experience this same issue? 

2. If you do, could you try it on Chrome as well. 

This will help me determine if it's a user specific issue, or a Edge/Chrome/Global Speed issue.

**Comment by Rangtian** [comment] 2021-01-29 02:12
Hi poly, I've tried Chrome. The latest Chrome suffers the same video rush while the latest Firefox doesn't. And I've had this only after the update of Edge, like two or three days ago. Global speed worked very well before the update. 

And from my observation, this kind of rush only happens on 60fps videos, like this one on Youtube.
https://www.youtube.com/watch?v=ZOEAPM_0Z6s

On Bilibili, the same video doesn't rush after I switch from 1080p@60 to 1080p@30.
https://www.bilibili.com/video/BV1Ji4y1g7Eb?p=17

Thank you.

**Comment by MasterGoodbytes** [comment] 2021-02-02 18:00
Hi, I'm having the exact same issue, and it started almost a week ago I think, just now I found where to report.
I use Chrome, and the video starts rushing with no input from me, to fix I have to go back a few seconds, but it happens several times in one video.

**Comment by polywock** [comment] 2021-02-03 05:14
Thanks for the video. Some users of Video Speed Controller are having similar issues. And people on the r/Chrome subreddit as well.  Seems to be a Chromium issue that's affecting certain people (or maybe an adblock issue).  60fps / sped up videos seems to be a common theme. 

https://github.com/igrigorik/videospeed/issues/761

https://github.com/igrigorik/videospeed/issues/762

https://www.reddit.com/r/chrome/comments/l81zxr/when_i_alt_tab_back_in_youtube_video_playing/

https://www.reddit.com/r/chrome/comments/l99uoq/youtube_videos_freeze_when_sped_up/

https://www.reddit.com/r/chrome/comments/l7v8ce/youtube_unusable_after_update/

https://amp.reddit.com/r/chrome/comments/l8n37l/issue_with_videos_on_the_latest_chrome_windows_10/

**Comment by polywock** [comment] 2021-02-03 05:18
Update: Confirmed Chromium bug. Issue has been reported and seems to already be fixed for Canary. The problem should be fixed in the Chrome/Edge update.

**Comment by Rangtian** [comment] 2021-02-03 09:28
Thank you poly. Good to know. 👍

**Closed** 2021-02-10 17:18 UTC
Labels: Chromium issue
