### ISSUE TITLE
Edge browser cannot be controlled using shortcut keys

### ISSUE THREAD

**Issue by kangx1987** [polywock/globalSpeed#423] opened 2023-10-13 10:27 UTC
I can't control it using shortcut keys in the latest version of Edge, but it works fine in Firefox. I disabled other Edge browser extensions but still can't use the shortcut keys. This problem occurred recently, and it has been working normally before.

**Comment by polywock** [comment] 2023-10-13 17:57
Seems very similar to this Issue. Apparently that was caused by a windows update, and was eventually fixed by a newer windows update. Have you checked if you have updates available? 

https://github.com/polywock/globalSpeed/issues/415

**Closed** 2024-09-04 19:46 UTC
